# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: 仓库检出
      uses: actions/checkout@v4
    - name: 设置 Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: 编译
      run: |
        pyinstaller -F -i images/icon.ico -w main.py
    - name: 移动文件
      run: |
        cp -r images dist/
    - name: 上传
      uses: actions/upload-artifact@v4
      with:
        name: CleanMyWeChat
        path: dist
